apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "guestbook-app.name" . }}-configmap"
  labels:
    {{- include "guestbook-app.labels" . | nindent 4 }}
data:
  redis-replica-host: "{{ .Release.Name }}-redis-replicas"
  redis-master-host: "{{ .Release.Name }}-redis-master"
  redisPort: {{ .Values.master.containerPorts.redis | quote }}
  redisPassword: {{ .Values.auth.password }}