apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "guestbook-app.name" . }}-configmap"
  labels:
    {{- include "guestbook-app.labels" . | nindent 4 }}
data:
  redisSlaveHost: {{ .Values.redisMaster.name }}
  redisMasterHost: {{ .Values.redisSlave.name }}
  redisPort: {{ .Values.master.containerPorts.redis }}
