apiVersion: v1
kind: Service
metadata:
  name: "{{ include "guestbook-app.name" . }}-service"
  labels:
    {{- include "guestbook-app.labels" . | nindent 4 }}
spec:
  ports:
  - protocol: {{ .Values.service.protocol}}
    port: {{ .Values.service.port  }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "guestbook-app.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
