apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-apps-of-apps
#  namespace: argocd
spec:
  destination:
    name: ''
    namespace: guestbook-app
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/arielrahamim/guestbook'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
