name: Docker Image CI

on:
  workflow_dispatch: 
  push:
    branches: [ "" ] # automatic ci disabled
    tags: [ 'v*' ] 
  pull_request:
    branches: [ "" ] 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: arielrahamim/guestbook:v1

