name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
     # with:
     #   token: ${{ github.token }}
    - name: Build the Docker image
      run: docker build ./guestbook-go/ --file ./guestbook-go/ --tag arielrahmim/guestbook:$(date +%s)
